export default [
  {
    userId: 1,
    name: 'user1',
    email: 'user1@gmail.com',
    password: 'user123',
    age: "27",
    blood: '2',
    current: "75",
    height: "170",
    desired: "65",
  },
  {
    userId: 2,
    name: 'user2',
    email: 'user2@gmail.com',
    password: 'user123',
    age: "20",
    blood: '4',
    current: "80",
    height: "165",
    desired: "56",
  },
  {
    userId: 3,
    name: 'user3',
    email: 'user3@gmail.com',
    password: 'user123',
    age: "45",
    blood: "1",
    current: "90",
    height: "174",
    desired: "60",
  },
];
